module.exports = {
  'oneClickIco': 'One-click ICO',
  'createHecoCoin': 'Create Heco chain token',
  'createBscCoin': 'Create BSC chain token',
  'tokenList': 'Token List',
  'connectWallet': 'Connect Wallet',
  'networkError': "Network Error",
  'tokenType': 'Token Type',
  'fixedSupply': 'Fixed Supply',
  'fixedDesc': 'Fixed total supply: The standard ERC20 token becomes one with a fixed total supply, and the total supply cannot be changed after issuance.',
  'issuanceOrBurn': 'Additional Issuance Or Burn',
  'moonMode': 'Moon Mode',
  'tokenName': 'Token Name',
  'charactorsTips': '1-64 characters',
  'charactorsTipsSymbol': '1-11 characters',
  'tokenAbbreviation': 'Token Abbreviation',
  'totalSupplay': 'Total Supply',
  'decimal': 'Decimal',
  'receivAddress': 'Receiving Address',
  'fee': 'Fee',
  'authorize': 'Approve',
  'create': 'Create ',
  'feeRatio': 'Fee Ratio',
  'dividendsRatio': 'Dividends Ratio',
  'liquidityRatio': 'Liquidity Ratio',
  'token': ' token',
  'leftDes': 'List your tokens on a platform with high efficiency and low gas fees, through CoinLaunch with a simple set-up process.',
  'coinTypeDesc': 'Support fixed volume, additional issuance and burn, Moon, etc.',
  'connect': 'Connect ',
  'netWork': ' Network',
  'typeText': 'Type Description',
  'typeText1': 'Token Type Description',
  'totalSupply': 'Total Supply',
  'type': 'Type',
  'balance': 'Balance',
  'operation': 'Operation',
  'createPool': 'Create Pool',
  'myToken': 'My Token',
  'noData': 'No Data',
  'tokenContractAddress': 'Token Contract Address',
  'settings': 'Parameter Settings',
  introduct: [
    'Fixed total supply?',
    'The standard token becomes one with a fixed total supply, and the total supply cannot be changed after issuance.',
    'Additional issuance or burn?',
    'additional issuance tokens are tokens compatible with standard tokens and have two additional functions: New token can be created and added to the total supply at any time, or the token in circulation can be burnt at any time.',
    'Moon mode?',
    'ach swap is subject to a fee at a certain ratio;The fee consists of two parts: dividends and liquidity increase.You can define the ratio of dividend and liquidity increase, which are both defaulted as 5 % by the system.Dividends: Allocated to all holders.Liquidity increase: Half of the dividends is swapped into YOU, and the other half is added to YouSwap liquidity.'
  ],
  waring: [
    'Please enter Token name',
    'Token name only can be entered letters and numbers',
    'Please enter Token abbreviation',
    'Token abbreviation only can be entered letters and numbers',
    'Please enter total supplay',
    'Total supplay enter only positive integers',
    'Please enter only decimal',
    'Decimal enter only positive integers',
    'Decimal ≤ 18',
  ],
  title: [
    '1.Fixed total supply',
    '2.Additional issuance or burn',
    '3.Moon mode',
    'Description of other attributes of tokens:',
    'Steps:'
  ],
  content: [
    'The standard token becomes one with a fixed total supply, and the total supply cannot be changed after issuance.',
    'additional issuance tokens are tokens compatible with standard tokens and have two additional functions: New token can be created and added to the total supply at any time, or the token in circulation can be burnt at any time.',
    'Token with dividend + automatic liquidity increase + burning',
    'The fee consists of two parts: dividends and liquidity increase. You can define the ratio of dividend and liquidity increase, which are both defaulted as 5% by the system.',
    'Dividends: Allocated to all holders.',
    'Liquidity increase: Half of the dividends is swapped into YOU, and the other half is added to YouSwap liquidity.Liquidity is permanently locked in YouSwap and cannot be withdrawn.',
    'Maximum transfer volume is 1/200 of the total supply, and the transfer shall fail if exceeding the limit.',
    'Liquidity adding threshold is 1/10 of the maximum transfer volume, and the liquidity will be added only after reaching the threshold.',
    'Minimum liquidity increase: When liquidity increase is triggered, half of the volume needs to be swapped. Therefore, during initial activation, it is necessary to ensure that the initial liquidity increase is greater than 1/3000 of the total supply. Otherwise, the tokens cannot be transferred.',
    '1. Issue token',
    '2. Click the button in the token list to activate the token.',
    'Activate: Activate Moon mode by adding liquidity in YouSwap. View the tutorial.',
    'Please create the initial liquidity of issued tokens and YOUs to activate the token, and the volume of issued tokens must be greater than 1/3000 of the total supply. Otherwise, the tokens cannot be transferred.',
    'For example, if the total supply is 3,000,000 XMoon, when the liquidity of XMoon/YOU is added, the volume of XMoon should be more than 3,000,000/3,000 = 1,000.',
  ]
}
