module.exports = {
  Home: 'Home',
  IDO: 'IDO',
  solgan: 'The decentralized exchange that truly belongs to you',
  WhitePaper: 'White Paper',
  NotStarted: 'Not Started',
  TotalRaise: 'Total Raise',
  MinAllocationL : 'Min Allocation',
  MaxAllocation: 'Max Allocation',
  StartTime: 'Start Time',
  EndTime: 'End Time',
  CheckIDODetails: 'Check IDO Details',
  ProductsHighlights: 'Products Highlights',
  RapidExchange: 'Stable high returns',
  mechanism: 'The mechanism of price feeding by Oracle Machine ensures the consistency of prices between on-chain and off-chain, and reduces the risk of uncertain loss of LP liquidity providers.',
  MultipleChainsDeployment: 'Multiple Chains Deployment',
  ecologies: 'Multiple public chains such as Ethereum, TRON mainnet, Binance smart chain and Huobi ecological interconnection.',
  Scalability: 'Layer 2 Scalability',
  performance: 'Scalability with high performance is under development, which may realize instant exchange and low Gas fee.',
  AggregationTrade: 'Cross-chain Aggregation Trade',
  EachDEX:'Each DEX service provider on multiple public chains integrate all kinds of DEX liquidity and pricing to provide users with optimal trading price and minimum slippage',
  Roadmap: 'Roadmap',
  Time1: 'March, 2021',
  store1: {
    one: 'YouSwap V1 version was released at the creation stage',
    two: '· Main net was launched on Ethereum',
    three: '· IDO function was available for YOU on YouStarter',
    four: '· Liquidity fund pool and invitation for mining were available',
    five: '· YOU, a protocol governance token, was released',
  },
  Time2: 'April, 2021',
  store2: {
    one: 'Columbus upgrade with a new version of YouSwap V1 released',
    two: '· Trading and mining functions are available',
    three: '· Main net is launched on TRON, BSC, and Heco',
    four: '· ICO function is available on YouStarter',
    five: '· DAO community autonomy',
  },
  Time3: 'May, 2021',
  store3: {
    one: 'Galileo upgrade with the version of YouSwap V2 released',
    two: '· Intelligent mining management system is available',
    three: '· Cross-chain aggregation trade function is available',
    four: '· Cross-chain aggregation trade function is available',
  },
  Time4: 'July, 2021',
  store4: {
    one: 'Darwin upgrade with the version of YouSwap V3 released',
    two: '· YouTreasury, a financial development program, is launched',
    three: '· Get through the Layer 2 scalability of ZK Rollup',
  },
  Time5: 'October, 2021',
  store5: {
    one: 'Faraday upgrade with the version of YouSwap V4 released',
    two: '· NFT market segment is developed and launched',
    three: '· Other protocols of Layer 2 are interoperable during the development',
    four: '· YouDerivatives is available',
  },
  Time6: 'January, 2022',
  store6: {
    one: 'Olympics upgrade with the version of YouSwap V5 released',
    two: '· Polkadot underlay cross-chain technology is developing',
    three: '· YouPay, a stable coin transfer service, is available',
    four: '· Synthetix protocol is bridged for brokerage',
  },
  TokenEcology: 'Token Ecology',
  InitialLiquidity:'Initial Liquidity',
  CommunityEcologyIncentive: 'Community Ecology Incentive',
  Investors: 'Investors',
  CoreTeam: 'Core Team',
  MiningBonus: 'Mining Bonus',
  Partners: 'Partners',
  media: 'Media',
  ContactUs: 'Contact Us',
  InProgress: 'In Progress',
  Participate: 'Participate',
  View: 'View',
  whitelisted: '* Current account is white listed',
  SwapAmount: 'Swap Amount',
  LeftTimeEnd: 'Estimated countdown',
  SwapProgress: 'Swap Progress',
  Pools: 'Pools',
  MyParticipate: 'My Participate',
  PoolInformation:'Pool Information',
  TokenAllocatedTime:'Token Allocated Time',
  MinimumSwapAmount:'Minimum Swap Amount',
  Qualification:'Qualification',
  whitelistparticipate:'Only the account in white list can participate in',
  Name:'Name',
  ContractAddress:'Contract Address',
  TotalSupply:'Total Supply',
  Holder:'Holder',
  Trades:'Trades',
  TokenInformation:'Token Information',
  Time:'Time',
  ParticipatingAmount:'Participating Amount (USDT)',
  ActualAmount:'Actual Amount (USDT)',
  Amount:'Amount (YOU)',
  Status:'Status',
  Success:'Success',
  Failed:'Failed',
  CurrentRate:'Current Rate',
  Authorize:'Approve',
  Authorized: 'Approved',
  Balance:'Balance',
  Swap:'Swap',
  Finish:'Finish',
  ConnectWallet:'Connect your wallet to check the status of the white list',
  ClickTelegram:'The current account is not in white list.',
  ClickTo:'Qualify for whitelist',
  whiteList:'',
  canParticipate:'Only the account in white list can participate in',
  StartTimwe:'Estimated countdown',
  ConnectWallet_add: 'Connect Wallet',
  InsufficientBalance: 'Insufficient USDT balance',
  startBlock: 'StartBlock',
  endBlock: 'EndBlock',
  priClick: 'Private round requires whitelist qualification, ',
  clickGet:'Qualify for whitelist',
  qualification: '',
  RemainingBlockchain: 'Remaining blockchain',
  Private: 'Private',
  public: 'Public',
  ClaimSuccess: 'Claim success',
  ClaimFailed: 'Claim failed',
  ClaimYOU: 'Claim YOU',
  Wrongnetwork: 'Wrong Network',
  noData: 'No record',
  Authorizeing: 'Approve...',
  AuthorizedSuccess: 'Approve Success',
  SwapFailed: 'Swap failed',
  SwapSuccess: 'Swap Success',
  Finished: 'Finish',
  GasPrice: 'Gas price',
  Medium: 'Medium',
  FastGwei: 'Fast',
  veryFast: 'Very fast',
  Audit_agency: 'Audit agency',
  viewRecord: 'View',
  detail_tips: 'The public round allows over-raising. After reaching the end block height, token collection and fund return will be carried out in proportion to the actual raised funds.',
  no: 'No',
  mining: 'Invite',
}
