module.exports = {
  Home: 'Home',
  IDO: 'IDO',
  solgan: 'The decentralized exchange that truly belongs to you',
  WhitePaper: 'White Paper',
  NotStarted: 'Not Started',
  TotalRaise: 'Total Raise',
  MinAllocationL: 'Min Allocation',
  MaxAllocation: 'Max Allocation',
  StartTime: 'Start Time',
  CheckIDODetails: 'Check IDO Details',
  ProductsHighlights: 'Products Highlights',
  RapidExchange: 'Rapid exchange',
  mechanism: 'The mechanism of price feeding by Oracle Machine ensures the consistency of prices between on-chain and off-chain, and reduces the risk of uncertain loss of LP liquidity providers.',
  MultipleChainsDeployment: 'Multiple Chains Deployment',
  ecologies: 'The ecologies of four big public chains including Ethereum, TRON’s main net,  Binance’s smart chain, and Huobi ecology were connected.',
  Scalability: 'Layer 2 Scalability',
  performance: 'Scalability with high performance is under development, which may realize instant exchange and low Gas fee.',
  AggregationTrade: 'Cross-chain Aggregation Trade',
  EachDEX: 'Each DEX service provider in the four public chains integrate all kinds of DEX liquidity and pricing to provide users with optimal trading and minimum slippage.',
  Roadmap: 'Roadmap',
  Time1: 'March, 2021',
  store1: {
    one: 'YouSwap V1 version was released at the creation stage',
    two: '· Main net was launched on Ethereum',
    three: '· IDO function was available for YOU on YouStarter',
    four: '· Liquidity fund pool and invitation for mining were available',
    five: '· YOU, a protocol governance token, was released',
  },
  Time2: 'April, 2021',
  store2: {
    one: 'Columbus upgrade with a new version of YouSwap V1 released',
    two: '· Trading and mining functions are available',
    three: '· Main net is launched on TRON, BSC, and Heco',
    four: '· ICO function is available on YouStarter',
    five: '· DAO community autonomy',
  },
  Time3: 'May, 2021',
  store3: {
    one: 'Galileo upgrade with the version of YouSwap V2 released',
    two: '· Intelligent mining management system is available',
    three: '· Intelligent mining management system is available',
    four: '· Cross-chain aggregation trade function is available',
  },
  Time4: 'July, 2021',
  store4: {
    one: 'Darwin upgrade with the version of YouSwap V3 released',
    two: '· YouTreasury, a financial development program, is launched',
    three: '· Get through the Layer 2 scalability of ZK Rollup',
  },
  Time5: 'October, 2021',
  store5: {
    one: 'Faraday upgrade with the version of YouSwap V4 released',
    two: '· NFT market segment is developed and launched',
    three: '· Other protocols of Layer 2 are interoperable during the development',
    four: '· YouDerivatives is available',
  },
  Time6: 'January, 2022',
  store6: {
    one: 'Olympics upgrade with the version of YouSwap V5 released',
    two: '· Polkadot underlay cross-chain technology is developing',
    three: '· YouPay, a stable coin transfer service, is available',
    four: '· Synthetix protocol is bridged for brokerage',
  },
  TokenEcology: 'Token Ecology',
  InitialLiquidity: 'Initial Liquidity',
  CommunityEcologyIncentive: 'Community Ecology Incentive',
  Investors: 'Investors',
  CoreTeam: 'Core Team',
  MiningBonus: 'Mining Bonus',
  Partners: 'Wallet Support',
  media: 'Media',
  ContactUs: 'Contact Us',
  InProgress: 'In Progress',
  Participate: 'Participate',
  View: 'View',
  whitelisted: '* Current account is white listed',
  SwapAmount: 'Swap Amount',
  LeftTimeEnd: 'Left Time to End',
  SwapProgress: 'Swap Progress',
  Pools: 'Pools',
  MyParticipate: 'My Participate',
  PoolInformation: 'Pool Information',
  TokenAllocatedTime: 'Token Allocated Time',
  MinimumSwapAmount: 'Minimum Swap Amount',
  Qualification: 'Qualification',
  whitelistparticipate: 'Only the account in white list can participate in',
  Name: 'Name',
  ContractAddress: 'Contract Address',
  TotalSupply: 'Total Supply',
  Holder: 'Holder',
  Trades: 'Trades',
  TokenInformation: 'Token Information',
  Time: 'Time',
  ParticipatingAmount: 'Participating Amount (USDT)',
  ActualAmount: 'Actual Amount (USDT)',
  Amount: 'Amount (YOU)',
  Status: 'Status',
  Success: 'Success',
  Failed: 'Failed',
  CurrentRate: 'Current Rate',
  Authorize: 'Approve',
  Balance: 'Balance',
  Swap: 'Swap',
  Finish: 'Finish',
  ConnectWallet: 'Connect your wallet to check the status of the white list',
  ClickTelegram: 'The current account is not in white list.',
  ClickTo: 'Qualify for whitelist',
  whiteList: '',
  canParticipate: 'Only the account in white list can participate in',
  StartTimwe: 'Left Time to Start',
  ConnectWallet_add: 'Connect Wallet',
  InsufficientBalance: 'Insufficient USDT balance',
  startBlock: 'StartBlock',
  endBlock: 'EndBlock',
  priClick: 'Private round requires whitelist qualification, ',
  clickGet: 'Qualify for whitelist',
  qualification: '',
  RemainingBlockchain: 'Remaining blockchain',
  Private: 'Private',
  liquidity: 'Invite',
  LiquidityDig: 'Pool',
  Quatation: 'Chart',
  CurrentTVL: 'TVL(USDT)',
  "当前价格": ' YOU Current Price',
  "YOU 余额": 'Your Balance',
  "待奖励金额": '待奖励金额',
  "总回购手续费": "Buyback Fee",
  "总回购销毁数量": 'Repurchased',
  "实时通缩率": 'Deflation Rate',
  "More": 'More',
  "Stacked": 'Staked',
  "Earned": 'Earned',
  "APY": 'APY',
  "当前挖矿产出": 'Minted (YOU)',
  "挖矿产出市值": 'Mining Output (USDT)',
  "YOU审计机构": 'Audit Agency',
  "24H交易额": 'Platform 24h volume (USDT)',
  "累积交易总额": 'Cumulative Volume (USDT)',
  "24H手续费": 'Platform 24h Fee (USDT)',
  "累积手续费": 'Cumulative Fee (USDT)',
  "流动性挖矿": 'Liquidity Mining',
  "title": "YouSwap",
  "平台币销毁列表": "Burned",
  "titleDesc": "The decentralized exchange that truly belongs to you",
  "contactUs": "Contact Us",
  "idoReport": "IDO Report",
  "liquidityReport": "Mining Report",
  "swapReport": "Swap Report",
  "invateReport": "Invite Report",
  "TimeData": "Time",
  "CoinType": "Token",
  "Count": "Amount",
  "NoWallet": "No wallet detected",
  "networkError": "Network Error",
  across_chain: {
    title: 'Bridge',
    across_title: 'YOU Cross-chain Bridge',
    across_titleDesc: 'Youswap provides the safest and fastest YOU cross-chain swap, enabling you to easily cross from Ethereum Mainnet to Heco.',
    Asset: 'Asset',
    From: 'From',
    To: 'To',
    EthereumMainnet: 'Ethereum Mainnet',
    Heco: 'Heco',
    TargetAddress: 'Target Address',
    EnterTheAddressOfHeco: 'Enter the address of Heco',
    Volume: 'Volume',
    MinVolume: 'Min. volume is 1000YOU',
    ConnectWallet: 'Connect Wallet',
    Dailylimit: 'Daily limit',
    Balance: 'Balance',
    InsufficientBalance: 'Insufficient balance',
    Maxvolume: 'Max. volume for cross-chain is',
    Minvolume: 'Min. volume for cross-chain is',
    YouWillReceive: 'You will receive',
    fee: 'You need to pay the gas fee for the target network as the cross-chain fee',
    desc: 'Due to the limited tokens in circulation at the initial stage upon the launch, YouSwap will, in order to guarantee the interests of users, limit the total volume of daily cross-chain until the restriction is lifted upon sufficient tokens in circulation.',
    Connected: 'Connected',
    SwapRecords: 'Swap records',
    Status: 'Status',
    SentVolume: 'Sent volume',
    SentVolumeDesc: ' (from Ethereum Mainnet)',
    ReceivedVolume: 'Received volume',
    ReceivedVolumeDesc: '(to Heco)',
    FeeTime: 'Fee/Time',
    Fee: 'Fee',
    Time: 'Time',
    Confirming: 'Confirming',
    Completed: 'Completed',
    Failed: 'Failed',
    Authorizing: 'Authorizing',
    AvailableBalance: 'Available balance',
    topLimit: 'Over conversion limit',
    walletAddressError: 'Please enter the correct wallet address',
    Swap: 'Swap',
    NetworkError: 'Network Error',
    ApproveSuccess: 'Approve Success',
    ApproveFaild: 'Approve Faild',
    InProcessing: 'In the processing',
    noRecord: 'No Record',
    toDayLimitDesc: "Since the circulation of YOU tokens in the initial stage of Heco's launch is small, in order to protect the interest of users, YouSwap limits the total amount of YOU cross-chain daily is 1 million. When the YOU circulation of the Heco network is sufficient, this restriction will be lifted."
  },
  network: {
    eth: 'Ethereum',
    heco: 'Heco',
    bsc: 'BSC',
    switch: 'Switch'
  },
  crossChain: 'Bridge',
  pledgeTotal: 'Total Value Locked',
  pledgeCurrer: 'Current TVL',
  Preview: 'Preview',
  Next: 'Next',
  Action: 'Action',
  dealTitle: 'Trading',
  dealDes: 'Reward YOU for each trade',
  stackTitle: 'Staking',
  stackDes: 'Stake token to earn YOU',
  docs: 'Docs',
  navDocs: 'Docs'
}
