module.exports = {
  Home: '首页',
  IDO: 'IDO',
  solgan: '真正属于你的去中心化交易所',
  WhitePaper: '白皮书',
  NotStarted: '未开始',
  TotalRaise: '总募集资金',
  MinAllocationL : '最低参与资金',
  MaxAllocation: '最高参与资金',
  StartTime: '开始时间',
  CheckIDODetails: '查看IDO详情',
  ProductsHighlights: '产品优势',
  RapidExchange: '快速兑换',
  mechanism: '预言机喂价的机制，保障链上与链下价格的一致性，减少了LP流动性提供者的无常损失风险。',
  MultipleChainsDeployment: '多链部署',
  ecologies: '以太坊、波场主网、币安智能链、火币生态四大公链上，打通各公链的生态。',
  Scalability: 'Layer 2 扩展',
  performance: '正在研发高性能的扩展性，未来可实现即时兑换和低Gas费用。',
  AggregationTrade: '跨链聚合交易',
  EachDEX:'四条公链上的各个DEX服务提供商集成整合各类DEX流动性和定价，为用户提供最优交易和最小滑点。',
  Roadmap: '路线图',
  Time1: '2021年3月',
  store1: {
    one: '创世阶段，上线YouSwap V1版本',
    two: '· 在以太坊上主网启动',
    three: '· YouStarter上线YOU的IDO功能',
    four: '· 流动性资金池及邀请挖矿上线',
    five: '· 正式发行协议治理代币YOU',
  },
  Time2: '2021年4月',
  store2: {
    one: '哥伦布升级，发布YouSwap V1新版本',
    two: '· 交易挖矿功能上线',
    three: '· 在波场、BSC、Heco上主网启动',
    four: '· YouStarter上线项目发币功能',
    five: '· DAO社区自治',
  },
  Time3: '2021年5月',
  store3: {
    one: '伽利略升级，上线YouSwap V2版本',
    two: '· 智能化挖矿管理系统上线',
    three: '· 多链聚合交易功能上线',
  },
  Time4: '2021年7月',
  store4: {
    one: '达尔文升级，上线YouSwap V3版本',
    two: '· 金融开发计划YouTreasury上线',
    three: '· 打通ZK Rollup二层扩展',
  },
  Time5: '2021年10月',
  store5: {
    one: '法拉第升级，上线YouSwap V4版本',
    two: '· NFT市场板块的开发上线',
    three: '· Layer2其他扩展方案开发互通',
    four: '· YouDerivatives衍生品上线',
  },
  Time6: '2022年1月',
  store6: {
    one: '奥林匹克升级，上线YouSwap V5版本',
    two: '· 对波卡底层跨链技术开发',
    three: '· 开发YouPay稳定币转账服务',
    four: '· 桥接Synthetix协议做大宗交易服务',
  },
  TokenEcology: '代币生态',
  InitialLiquidity:'初始流动性',
  CommunityEcologyIncentive: '社区生态激励',
  Investors: '投资者',
  CoreTeam: '核心团队',
  MiningBonus: '挖矿奖励',
  Partners: '合作伙伴',
  media: '媒体',
  ContactUs: '联系我们',
  InProgress: '进行中',
  Participate: '参与',
  View: '查看',
  whitelisted: '* 当前账户为白名单账户',
  SwapAmount: '兑换数量',
  LeftTimeEnd: '距离结束',
  SwapProgress: '兑换进度',
  Pools: '兑换池详情',
  MyParticipate: '我的参与',
  PoolInformation:'兑换池信息',
  TokenAllocatedTime: '代币分配时间',
  MinimumSwapAmount: '项目成功最低兑换数量',
  Qualification: '参与限制',
  whitelistparticipate: '仅白名单可参与',
  Name: '名称',
  ContractAddress: '合约地址',
  TotalSupply: '总供应量',
  Holder: '持币人',
  Trades: '交易笔数',
  TokenInformation:'代币信息',
  Time:'时间',
  ParticipatingAmount:'参与数量（USDT)',
  ActualAmount:'实际成功数量（USDT)',
  Amount:'数量（YOU)',
  Status:'状态',
  Success:'成功',
  Failed:'失败',
  CurrentRate:'当前比例',
  Authorize:'授权',
  Balance:'余额',
  Swap:'兑换',
  Finish:'完成',
  ConnectWallet:'连接钱包查看白名单状态',
  ClickTelegram:'当前账户未非白名单账户，',
  ClickTo: '点击获取',
  whiteList:'白名单资格',
  canParticipate:'仅白名单可参与',
  StartTimwe:'距离开始',
  ConnectWallet_add: '连接钱包',
  InsufficientBalance: '余额不足',
  startBlock: '开始块高',
  endBlock: '结束块高',
  priClick: '私有轮需要白名单资格，',
  clickGet:'点击获取',
  qualification: '资格',
  RemainingBlockchain: '剩余区块',
  Private: '私有轮',
  liquidity: '流动性',
  LiquidityDig: '挖矿',
  Quatation: '行情',
  CurrentTVL: '当前流动性(USDT）',
  "当前价格": 'YOU 当前价格',
  "YOU 余额": 'YOU 余额',
  "总回购手续费": "总回购手续费",
  "待奖励金额": '待奖励金额',
  "总回购销毁数量": '总销毁数量',
  "实时通缩率": '实时通缩率',
  "More": '更多',
  "Stacked": '质押币对',
  "Earned": '收益币种',
  "APY": '年化',
  "当前挖矿产出": '当前挖矿产出(YOU)',
  "挖矿产出市值": '挖矿产出市值(USDT)',
  "YOU审计机构": 'YOU审计机构',
  "24H交易额": '24H交易额(USDT）',
  "累积交易总额": '累积交易总额(USDT）',
  "24H手续费": '24H手续费(USDT）',
  "累积手续费": '累积手续费(USDT）',
  "流动性挖矿": '流动性挖矿',
  "平台币销毁列表": "平台币销毁列表",
  "titleDesc": "真正属于你的去中心化交易所",
  "contactUs": "联系我们",
  "idoReport": "IDO 报告",
  "liquidityReport": "流动性挖矿报告",
  "swapReport": "兑换 报告",
  "invateReport": "邀请挖矿报告",
  "TimeData": "时间",
  "CoinType": "币种",
  "Count": "数量",
  "NoWallet": "未检测到钱包",
  "networkError": "网络错误",
  network: {
    eth: '以太坊主网',
    heco: '火币生态链',
    switch: '切换至'
  },
  crossChain: '跨链桥',
  pledgeTotal: '总锁仓量(USDT)'
}
