module.exports = {
  Home: '首页',
  IDO: 'IDO',
  solgan: '真正属于你的去中心化交易所',
  WhitePaper: '白皮书',
  NotStarted: '未开始',
  TotalRaise: '总募集资金',
  MinAllocationL: '最低参与资金',
  MaxAllocation: '最高参与资金',
  StartTime: '开始时间',
  CheckIDODetails: '查看IDO详情',
  ProductsHighlights: '产品优势',
  RapidExchange: '快速兑换',
  mechanism: '预言机喂价的机制，保障链上与链下价格的一致性，减少了LP流动性提供者的无常损失风险。',
  MultipleChainsDeployment: '多链部署',
  ecologies: '以太坊、波场主网、币安智能链、火币生态四大公链上，打通各公链的生态。',
  Scalability: 'Layer 2 扩展',
  performance: '正在研发高性能的扩展性，未来可实现即时兑换和低Gas费用。',
  AggregationTrade: '跨链聚合交易',
  EachDEX: '四条公链上的各个DEX服务提供商集成整合各类DEX流动性和定价，为用户提供最优交易和最小滑点。',
  Roadmap: '路线图',
  Time1: '2021年3月',
  store1: {
    one: '创世阶段，上线YouSwap V1版本',
    two: '· 在以太坊上主网启动',
    three: '· YouStarter上线YOU的IDO功能',
    four: '· 流动性资金池及邀请挖矿上线',
    five: '· 正式发行协议治理代币YOU',
  },
  Time2: '2021年4月',
  store2: {
    one: '哥伦布升级，发布YouSwap V1新版本',
    two: '· 交易挖矿功能上线',
    three: '· 在波场、BSC、Heco上主网启动',
    four: '· YouStarter上线项目发币功能',
    five: '· DAO社区自治',
  },
  Time3: '2021年5月',
  store3: {
    one: '伽利略升级，上线YouSwap V2版本',
    two: '· 智能化挖矿管理系统上线',
    three: '· 多链聚合交易功能上线',
  },
  Time4: '2021年7月',
  store4: {
    one: '达尔文升级，上线YouSwap V3版本',
    two: '· 金融开发计划YouTreasury上线',
    three: '· 打通ZK Rollup二层扩展',
  },
  Time5: '2021年10月',
  store5: {
    one: '法拉第升级，上线YouSwap V4版本',
    two: '· NFT市场板块的开发上线',
    three: '· Layer2其他扩展方案开发互通',
    four: '· YouDerivatives衍生品上线',
  },
  Time6: '2022年1月',
  store6: {
    one: '奥林匹克升级，上线YouSwap V5版本',
    two: '· 对波卡底层跨链技术开发',
    three: '· 开发YouPay稳定币转账服务',
    four: '· 桥接Synthetix协议做大宗交易服务',
  },
  TokenEcology: '代币生态',
  InitialLiquidity: '初始流动性',
  CommunityEcologyIncentive: '社区生态激励',
  Investors: '投资者',
  CoreTeam: '核心团队',
  MiningBonus: '挖矿奖励',
  Partners: '钱包支持',
  media: '媒体',
  ContactUs: '联系我们',
  InProgress: '进行中',
  Participate: '参与',
  View: '查看',
  whitelisted: '* 当前账户为白名单账户',
  SwapAmount: '兑换数量',
  LeftTimeEnd: '距离结束',
  SwapProgress: '兑换进度',
  Pools: '兑换池详情',
  MyParticipate: '我的参与',
  PoolInformation: '兑换池信息',
  TokenAllocatedTime: '代币分配时间',
  MinimumSwapAmount: '项目成功最低兑换数量',
  Qualification: '参与限制',
  whitelistparticipate: '仅白名单可参与',
  Name: '名称',
  ContractAddress: '合约地址',
  TotalSupply: '总供应量',
  Holder: '持币人',
  Trades: '交易笔数',
  TokenInformation: '代币信息',
  Time: '时间',
  ParticipatingAmount: '参与数量（USDT)',
  ActualAmount: '实际成功数量（USDT)',
  Amount: '数量（YOU)',
  Status: '状态',
  Success: '成功',
  Failed: '失败',
  CurrentRate: '当前比例',
  Authorize: '授权',
  Balance: '余额',
  Swap: '兑换',
  Finish: '完成',
  ConnectWallet: '连接钱包查看白名单状态',
  ClickTelegram: '当前账户未非白名单账户，',
  ClickTo: '点击获取',
  whiteList: '白名单资格',
  canParticipate: '仅白名单可参与',
  StartTimwe: '距离开始',
  ConnectWallet_add: '连接钱包',
  InsufficientBalance: '余额不足',
  startBlock: '开始块高',
  endBlock: '结束块高',
  priClick: '私有轮需要白名单资格，',
  clickGet: '点击获取',
  qualification: '资格',
  RemainingBlockchain: '剩余区块',
  Private: '私有轮',
  liquidity: '邀请挖矿',
  LiquidityDig: '挖矿',
  Quatation: '行情',
  CurrentTVL: '当前流动性(USDT）',
  "当前价格": 'YOU 当前价格',
  "YOU 余额": 'YOU 余额',
  "总回购手续费": "总回购手续费",
  "待奖励金额": '待奖励金额',
  "总回购销毁数量": '总销毁数量',
  "实时通缩率": '实时通缩率',
  "More": '更多',
  "Stacked": '质押币对',
  "Earned": '收益币种',
  "APY": '年化',
  "当前挖矿产出": '当前挖矿产出(YOU)',
  "挖矿产出市值": '挖矿产出市值(USDT)',
  "YOU审计机构": '审计机构',
  "24H交易额": '24H交易额(USDT）',
  "累积交易总额": '累积交易总额(USDT）',
  "24H手续费": '24H手续费(USDT）',
  "累积手续费": '累积手续费(USDT）',
  "流动性挖矿": '流动性挖矿',
  "平台币销毁列表": "平台币销毁列表",
  "title": "YouSwap",
  "titleDesc": "真正属于你的去中心化交易所",
  "contactUs": "联系我们",
  "idoReport": "IDO 报告",
  "liquidityReport": "流动性挖矿报告",
  "swapReport": "兑换 报告",
  "invateReport": "邀请挖矿报告",
  "TimeData": "时间",
  "CoinType": "币种",
  "Count": "数量",
  "NoWallet": "未检测到钱包",
  "networkError": "网络错误",
  "across_title": "YOU跨链桥",
  "across_titleDesc": "YouSwap提供了最安全，最快捷的YOU跨链转换， 让您轻松实现从以太坊主网跨链到火币主链",
  across_chain: {
    title: '跨链桥',
    across_title: 'YOU 跨链桥',
    across_titleDesc: 'Youswap提供了最安全，最快捷的YOU跨链转换，让您轻松实现从以太坊主网跨链到火币生态链',
    Asset: '币种',
    From: '从',
    To: '到',
    EthereumMainnet: '以太坊主网',
    Heco: '火币生态链',
    TargetAddress: '目标地址',
    EnterTheAddressOfHeco: '输入火币生态链地址',
    Volume: '数量',
    MinVolume: '最小跨链数量1000YOU',
    ConnectWallet: '连接钱包',
    Dailylimit: '每日跨链限额',
    Balance: '余额',
    InsufficientBalance: '余额不足',
    Maxvolume: '最大跨链数量为',
    Minvolume: '最小跨链数量为',
    YouWillReceive: '您将收到',
    fee: '您需要支付目标网络的gas费作为跨链手续费',
    desc: '由于上线初期代币流通量较少，为保证用户利益，YouSwap限制每日跨链的总量，当代币流通量充足后，将取消此限制',
    Connected: '已连接',
    SwapRecords: '转换记录',
    Status: '状态',
    SentVolume: '发送数量',
    SentVolumeDesc: '(从以太坊主网)',
    ReceivedVolume: '接收数量',
    ReceivedVolumeDesc: '(火币生态链)',
    FeeTime: '手续费/时间',
    Fee: '手续费',
    Time: '时间',
    Confirming: '确认中',
    Completed: '完成',
    Failed: '失败',
    Authorizing: '授权中',
    AvailableBalance: '可用余额',
    topLimit: '到达今日转换上线',
    walletAddressError: '请输入正确的钱包地址',
    Swap: '转换',
    NetworkError: '网络错误',
    ApproveSuccess: '授权成功',
    ApproveFaild: '授权失败',
    InProcessing: '处理中',
    noRecord: '无转换记录',
    toDayLimitDesc: '由于Heco网络上线初期YOU代币流通量较少，为保证用户利益，Youswap限制每日跨链的YOU总量为100万，当Heco网络的YOU流通量充足后，将取消此限制'
  },
  network: {
    eth: '以太坊主网',
    heco: '火币生态链',
    bsc: '币安智能链',
    switch: '切换至'
  },
  crossChain: '跨链桥',
  pledgeTotal: '总锁仓量',
  pledgeCurrer: '当前锁仓量',
  Preview: '上一页',
  Next: '下一页',
  Action: '操作',
  dealTitle: '交易挖矿',
  dealDes: '完成交易就送YOU奖励',
  stackTitle: '质押挖矿',
  stackDes: '质押Token赚取YOU奖励',
  docs: '文档',
  navDocs: '教程'
}
